Use matrix structural analysis to find the nodal displacements and reaction forces for the following system.

<img src="img/geometry.jpeg" />

The material properties are defined as  
$E = 200$  
$\nu = 0.3$  
$A = 6,000$  
$I_y = I_z = 200 \times 10^6$  
$J = 300 \times 10^3$  

In [ ]:
# IMPORT 
# import the required libraries and classes 

import numpy as np
import math
import matrixStructAnalysis as MSA
from matrixStructAnalysis import Nodes
from matrixStructAnalysis import Elements

# DEFINE GEOMETRY
# define the geometry of the problem

# each row is a node defined in (x, y, z) coordinates
nodes = np.array([[8e3, 0, 0],
                  [13e3, 0, 0]])

# the load applied at each node as (Fx, Fy, Fz, Mx, My, Mz)
load = np.array([[0,0,0,0,0,0],
                 [5/math.sqrt(2),-5/math.sqrt(2),0,0,0,0]])

# the type of boundary condition
BC = np.array([[0,0,0,0,0,0],
               [1,1,1,1,1,1]])

# which nodes are connected to form elements
# each row is a new elements with end points (node0, node1)
connections = np.array([[0, 1]])

# material properties
# enter the material properties for each element
# the index corresponds to the element index
E = np.array([200])
nu = np.array([0.3])
A = np.array([6e3])
Iz = np.array([200e6])
Iy = np.array([200e6])
Ip = np.array([10])
J = np.array([300e3])

# DEFINE CLASSES
Nodes = Nodes(nodes=nodes,load=load,BC=BC)
Elements = Elements(connections,E,nu,A,Iz,Iy,Ip,J)

# RUN THE SOLVER
displacement, forces = MSA.run_MSA_solver(Nodes,Elements)

print("[DOF Index, Displacements]")
print(displacement)
print("Forces")
print(forces)



New code for running A2 P2  
(not done yet)


In [2]:
import numpy as np
import scipy as sp
import math
import matrixStructAnalysis as MSA
from matrixStructAnalysis import Nodes
from matrixStructAnalysis import Elements

# DEFINE GEOMETRY
# define the geometry of the problem

# each row is a node defined in (x, y, z) coordinates
nodes = np.array([[0, 0, 0],
                  [30, 40, 0]] )

# the load applied at each node as (Fx, Fy, Fz, Mx, My, Mz)
load = np.array([[0,0,0,0,0,0],
                 [-0.6, -0.8,0,0,0,0]])

# the type of boundary condition
BC = np.array([[0,0,0,0,0,0],
               [1,1,1,1,1,1]])

# which nodes are connected to form elements
# each row is a new elements with end points (node0, node1)
connections = np.array([[0, 1]])

# material properties
# enter the material properties for each element
# the index corresponds to the element index

r = 1

E = np.array([1000])
nu = np.array([0.3])
A = np.array([np.pi * r ** 2])
Iz = np.zeros(1) + math.pi * r**4 / 4
Iy = np.zeros(1) + math.pi * r**4 / 4
I_rho = np.zeros(1) + math.pi * r**4 / 2
J = np.zeros(1) + math.pi * r**4 / 2


# DEFINE CLASSES
Nodes = Nodes(nodes=nodes,load=load,BC=BC)
Elements = Elements(connections,E,nu,A,Iz,Iy,I_rho,J)

# RUN THE SOLVER
result = MSA.run_buckling_part(Nodes,Elements)

print(result)

[[ 0.6  0.8  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [-0.8  0.6  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  -0.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.6  0.8  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  -0.8  0.6  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  -0.   1.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.6  0.8  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.  -0.8  0.6  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.   1.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.6  0.8  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.8  0.6  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.   1. ]]
[[ 6.00000000e-01]
 [ 8.00000000e-01]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 9.48893741e-16]
 [-6.00000000e-01]
 [-8.00000000e-01]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
3.684786773712

Code for the first example problem.   
A2P1 - In Class review part 1

In [1]:
import numpy as np
import math
import matrixStructAnalysis as MSA
from matrixStructAnalysis import Nodes
from matrixStructAnalysis import Elements

# DEFINE GEOMETRY
# define the geometry of the problem

# each row is a node defined in (x, y, z) coordinates
nodes = np.array([[0, 0, 10],
                  [15, 0, 10],
                  [15, 0, 0]])

# the load applied at each node as (Fx, Fy, Fz, Mx, My, Mz)
load = np.array([[0,0,0,0,0,0],
                 [0.1,0.05,-0.07,0.05,-0.1,0.25],
                 [0,0,0,0,0,0]])

# the type of boundary condition
BC = np.array([[0,0,0,0,0,0],
               [1,1,1,1,1,1],
               [0,0,0,1,1,1]])

# which nodes are connected to form elements
# each row is a new elements with end points (node0, node1)
connections = np.array([[0, 1],
                        [1, 2]])

# material properties
# enter the material properties for each element
# the index corresponds to the element index

b = 0.5
h = 1

E = np.array([1000,1000])
nu = np.array([0.3,0.3])
A = np.array([b*h,b*h])
Iz = np.array([b*h**3/12,b*h**3/12])
Iy = np.array([h*b**3/12,h*b**3/12])
Ip = np.array([b*h/(12*(b**2+h**2)),b*h/(12*(b**2+h**2))])
J = np.array([0.02861,0.02861])

local_z = np.array([[0, 0, 1], 
                    [1,0,0]])

# DEFINE CLASSES
Nodes = Nodes(nodes=nodes,load=load,BC=BC)
Elements = Elements(connections,E,nu,A,Iz,Iy,Ip,J,local_z)

# RUN THE SOLVER
displacement, forces = MSA.run_MSA_solver(Nodes,Elements)

print("DOF, Displacements")
print(displacement)
print("Node DOF, Forces")
print(forces)



DOF, Displacements
[[ 6.00000000e+00  2.84049953e-03]
 [ 7.00000000e+00  1.59843349e+00]
 [ 8.00000000e+00 -1.30609178e-03]
 [ 9.00000000e+00 -1.47204342e-01]
 [ 1.00000000e+01 -1.67293339e-02]
 [ 1.10000000e+01  1.82343349e-01]
 [ 1.50000000e+01 -1.66162853e-01]
 [ 1.60000000e+01  8.79074190e-03]
 [ 1.70000000e+01  1.82343349e-01]]
Node DOF, Forces
[[ 0.00000000e+00 -9.46833175e-02]
 [ 1.00000000e+00 -3.42012405e-02]
 [ 2.00000000e+00  4.69541098e-03]
 [ 3.00000000e+00  1.07987595e-01]
 [ 4.00000000e+00 -2.35979893e-02]
 [ 5.00000000e+00 -7.63018607e-01]
 [ 1.20000000e+01 -5.31668247e-03]
 [ 1.30000000e+01 -1.57987595e-02]
 [ 1.40000000e+01  6.53045890e-02]]


In Class Example #2
A2P1 - In Class review part 1

In [2]:
import numpy as np
import math
import matrixStructAnalysis as MSA
from matrixStructAnalysis import Nodes
from matrixStructAnalysis import Elements

# DEFINE GEOMETRY
# define the geometry of the problem

# each row is a node defined in (x, y, z) coordinates
nodes = np.array([[0, 0, 0],
                  [-5, 1, 10],
                  [-1, 5, 13],
                  [-3, 7, 11],
                  [6, 9, 5]])

# the load applied at each node as (Fx, Fy, Fz, Mx, My, Mz)
load = np.array([[0,0,0,0,0,0],
                 [0.1,-0.05,-0.075,0,0,0],
                 [0,0,0,0.5,-0.1,0.3],
                 [0,0,0,0,0,0],
                 [0,0,0,0,0,0]])

# the type of boundary condition
# 0 = fixed
# 1 = free
BC = np.array([[1,1,0,1,1,1],
               [1,1,1,1,1,1],
               [1,1,1,1,1,1],
               [0,0,0,0,0,0],
               [0,0,0,1,1,1],])

# which nodes are connected to form elements
# each row is a new elements with end points (node0, node1)
connections = np.array([[0, 1],
                        [1, 2],
                        [2, 3],
                        [2, 4]])

# material properties
# enter the material properties for each element
# the index corresponds to the element index

r = 1

E = np.zeros(4) + 500
nu = np.zeros(4) + 0.3
A = np.zeros(4) + math.pi * r**2
Iz = np.zeros(4) + math.pi * r**4 / 4
Iy = np.zeros(4) + math.pi * r**4 / 4
Ip = np.zeros(4) + math.pi * r**4 / 2
J = np.zeros(4) + math.pi * r**4 / 2

#local_z = np.array([[0, 0, 1], 
#                    [1,0,0]])

# DEFINE CLASSES
Nodes = Nodes(nodes=nodes,load=load,BC=BC)
Elements = Elements(connections,E,nu,A,Iz,Iy,Ip,J)

# RUN THE SOLVER
displacement, forces = MSA.run_MSA_solver(Nodes,Elements)

print("Displacements")
print(displacement)
print("Forces")
print(forces)


Displacements
[[ 0.00000000e+00  1.62974224e-01]
 [ 1.00000000e+00  6.75373057e-02]
 [ 3.00000000e+00  3.86030440e-03]
 [ 4.00000000e+00 -9.77672000e-03]
 [ 5.00000000e+00  9.97704371e-03]
 [ 6.00000000e+00  5.68382275e-02]
 [ 7.00000000e+00 -2.12726063e-02]
 [ 8.00000000e+00 -4.42346868e-02]
 [ 9.00000000e+00  3.95566400e-03]
 [ 1.00000000e+01 -9.29992199e-03]
 [ 1.10000000e+01  9.97704371e-03]
 [ 1.20000000e+01  1.04442565e-03]
 [ 1.30000000e+01  1.09052066e-03]
 [ 1.40000000e+01  3.46317799e-04]
 [ 1.50000000e+01  3.13555692e-03]
 [ 1.60000000e+01 -4.00549583e-03]
 [ 1.70000000e+01  5.14273247e-03]
 [ 2.70000000e+01 -4.55166275e-03]
 [ 2.80000000e+01  4.90188046e-04]
 [ 2.90000000e+01  6.64257197e-04]]
Forces
[[ 2.00000000e+00  6.67219970e-03]
 [ 1.80000000e+01 -2.35127129e-02]
 [ 1.90000000e+01  1.37948249e-01]
 [ 2.00000000e+01  2.53249828e-02]
 [ 2.10000000e+01 -4.11610746e-01]
 [ 2.20000000e+01  2.98118234e-01]
 [ 2.30000000e+01 -3.61440337e-01]
 [ 2.40000000e+01 -7.64872871e-02